fix: environment variable loading issues

diff --git a/.taskfiles/nke.yaml b/.taskfiles/nke.yaml
--- a/.taskfiles/nke.yaml
+++ b/.taskfiles/nke.yaml
@@ -1,15 +1,11 @@
 version: '3'
 
-vars:
-  REQUIRED_TOOLS_LIST: kubectl,kubectl-karbon
-  K8S_DISTRO_NAME: 'Nutanix Kubernetes Engine (NKE)'
-
 tasks:
 
   default:
   - task: :helpers:validate
     vars:
-      REQUIRED_TOOLS_LIST: "{{.REQUIRED_TOOLS_LIST}}"
+      REQUIRED_TOOLS_LIST: kubectl,kubectl-karbon
 
   download-creds:
     deps: [default]
@@ -19,8 +15,8 @@ tasks:
       msg: "${HOME}/.kube doesn't exist, please create and try again."
     desc: Download NKE kubeconfig for specific cluster
     cmds:
-    - 'KARBON_PASSWORD="{{.PRISM_CENTRAL_PASS}}" kubectl karbon login -u {{.PRISM_CENTRAL_USER}} --server {{.PRISM_CENTRAL_ENDPOINT}} --cluster {{.K8S_CLUSTER_NAME}} --force --insecure'
-    - 'kubectl config view --raw --minify | tee ${HOME}/.kube/{{.K8S_CLUSTER_NAME}}.cfg'
+    - 'KARBON_PASSWORD="${PRISM_CENTRAL_PASS}" kubectl karbon login -u ${PRISM_CENTRAL_USER} --server ${PRISM_CENTRAL_ENDPOINT} --cluster ${K8S_CLUSTER_NAME} --force --insecure'
+    - 'kubectl config view --raw --minify | tee ${HOME}/.kube/${K8S_CLUSTER_NAME}.cfg'
     requires:
       vars: [K8S_CLUSTER_NAME, PRISM_CENTRAL_PASS, PRISM_CENTRAL_USER, PRISM_CENTRAL_ENDPOINT]
 
@@ -38,5 +34,11 @@ tasks:
       K8S_CLUSTER_NAME:
         sh: 'KARBON_PASSWORD="{{.PRISM_CENTRAL_PASS}}" kubectl karbon login -u {{.PRISM_CENTRAL_USER}} --server {{.PRISM_CENTRAL_ENDPOINT}} --force --insecure | kubectl config view --raw --minify -o jsonpath="{.clusters[0].name}"'
     cmds:
-    - 'kubectl config view --raw --minify | tee ${HOME}/.kube/{{.K8S_CLUSTER_NAME}}.cfg'
+    - |
+      if [ "$(kubectl config view --raw --minify -o jsonpath='{.clusters[0].name}')" == "{{.K8S_CLUSTER_NAME}}" ]; then
+        kubectl config view --raw --minify | tee ${HOME}/.kube/{{.K8S_CLUSTER_NAME}}.cfg
+      else
+        echo "ERROR: Failed to either connect to Prism Central ( {{.PRISM_CENTRAL_ENDPOINT}} ) and retrieve valid NKE Cluster. Please Try Again."
+        exit 1
+      fi
     interactive: true
