Multiple Features and Bug Fixes (#7)
* add: initial profile for nai-llm-k8s
* add: cluster-configs for new cluster nai-llm
* fix: ingress addons missing
* fix: bootstrapping docs
* fix: gpu troubleshooting collection
* fix: nai-llm model and revision being used
* fix: updated nai-llm-helm with huggingface token when useExistingNFS is False
* fix: updated cluster configs with hf token
* fix: hugging face token added to nai-utils docker image
* fix: add HF_TOKEN to clusterstorage container
* fix: bump version for nai-utils docker image and nai-helm chart
* add: cluster-configs for new cluster nai-llm-gitops-mgmt
* remove: k8s dashboard on base profile
* add: cluster-configs for new cluster nai-llm-gitops-nonp
* fix: add components
* fix: setting self-signed cluster issue as default
* fix: self-signed kustomization
* add: kube-vip and ingress nginx for kind cluster
* fix: ingress nginx deploy
* fix: kind wildcard domain for istio ingress
* fix: kind local wilcard_ingress_subdomain
* add: cluster-configs for new cluster flux-kind-local
* add: helm_chart version overrides
* fix: cleanup support gpt profiles
* add: cluster-configs for new cluster supportgpt-prod-k8
* fix: temp remove letsencryp issuer
* fix: nginx_ingress issues
* fix: gpu_operator version issues
* add: cluster-configs for new cluster supportgpt-prod-k8
* fix: letsencrypt cluster issuer
* fix: modified minimal cert-manager version that supports latest fixes to route53
* fix: disable issuer aws
* fix: re-enable aws route53
* fix: enabling/disabling of each service with ability to override version
* fix: knative-eventing path
* fix: temp remove addons to resolve pathing issues
* fix: knative versions in url
* fix: knative istio dependencies
* fix: knative-istio dependencies
* multiple minor
* fix: aws lets encrypt configs
* fix: migrate ip,domain and hostname details into secrets
* fix: cherry-pick out secrets
* add: cluster-configs for new cluster nai-llm-gitops-prod
* fix: kserve pathing
* fix: kserve relative pathing for addons
* fix: kserve-deploy name in kustomization
* fix: non-prod kserve-deploy
* fix: quote on existingnfs issue
* fix: secrets handling
* fix: letsencrypt issuer with component vs. kustomization api
* add: cluster-configs for new cluster nai-llm-gitops-prod
* fix: kind cluster add-ons
* add: cert-manager lets encrypt for other profiles
* fix: letsencrypt ordering
* fix: knative-serving dependencies
* fix: force overrite of immutable objects
* fix: dependency issues
* fix: remove knative pod-deploy option
* fix: milvus bucket being missing
* fix: milvus bucket key reference
* fix: update cluster info
* fix: letsencrypt components
* fix: added required packages also to brewfile
* fix: cert-manager version
* fix: brewfile packages to include gomplate and other required tools
* add: cluster-configs for new cluster flux-kind-cicd
* add: cluster-configs for new cluster flux-kind-local
* fix: add kind-stacks minimal profile
* add: cluster-configs for new cluster flux-kind-cicd
* fix: minimal profile
* fix: github actions and kind cluster for cicd workflow
* fix: e2e cluster name
* fix: flux naming
* fix: re-add in configmaps for cicd use case
* fix: gitignore for example yaml config
* fix: add example yaml config for local kind cluster
* fix: removed awscli from brewfile to avoid build breaks in macos-12
* add: load dotfiles task for net new builds
* fix: install_zsh permission bit
* fix: message in dotfile task
* fix: load dotfiles scripts
* add: install-zsh and devbox
* add: install zsh and devbox tasks to get around not having/needing docker
* fix: leverage debian as os-release check vs. ubuntu
* fix: issue with decrypting file when doing bootstrap testing
* add: cluster-configs for new cluster nke-nvd-llm-mgmt-02
* add: cluster-configs for new cluster nke-nvd-llm-wkl-02
* fix: added tmux

diff --git a/.taskfiles/sops.yaml b/.taskfiles/sops.yaml
--- a/.taskfiles/sops.yaml
+++ b/.taskfiles/sops.yaml
@@ -8,9 +8,12 @@ tasks:
       REQUIRED_TOOLS_LIST: sops,age-keygen
 
   decrypt:
-    desc: decrypts sops file located in clusters/$K8S_CLUSTER_NAME/platform/cluster-secrets.sops.yaml
+    desc: decrypts sops file located in clusters/<K8S_CLUSTER_NAME>/platform/cluster-secrets.sops.yaml
+    vars:
+      AGE_PUBLIC_KEY:
+        sh: age-keygen -y {{.SOPS_AGE_KEY_FILE}}
     cmds:
-    - sops --decrypt clusters/${K8S_CLUSTER_NAME}/platform/cluster-secrets.sops.yaml
+    - sops --decrypt --age {{.AGE_PUBLIC_KEY}} clusters/${K8S_CLUSTER_NAME}/platform/cluster-secrets.sops.yaml
     requires:
       vars: [K8S_CLUSTER_NAME]
 
@@ -24,9 +27,30 @@ tasks:
   encrypt:
     vars:
       CLUSTER_PLATFORM_DIR: "{{.ROOT_DIR}}/clusters/${K8S_CLUSTER_NAME}/platform"
-    cmd: sops --encrypt --in-place {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml
+      AGE_PUBLIC_KEY:
+        sh: age-keygen -y {{.SOPS_AGE_KEY_FILE}}
+    cmds:
+    - sops --encrypt --in-place --age {{.AGE_PUBLIC_KEY}} {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml
+    - task: :sops:check-encrypted-file
     deps: [age-keygen]
     preconditions:
     - {msg: "Missing Sops Age key file", sh: "test -f {{.SOPS_AGE_KEY_FILE}}"}
+    requires:
+      vars: [K8S_CLUSTER_NAME]
+
+  check-encrypted-file:
+    internal: true
+    silent: true
+    cmds:
+    - |
+      if grep -q -i sops {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml; then
+        echo "Cluster Secrets have been successully encrypted"
+      else
+        echo "Cluster Secrets failed to be properly encrypted, see {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml to troubleshoot"
+        exit 1
+      fi
+    preconditions:
+    - sh: test -f {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml
+      msg: "Missing {{.CLUSTER_PLATFORM_DIR}}/cluster-secrets.sops.yaml"
     requires:
       vars: [K8S_CLUSTER_NAME]
